- name: Declare variable at play level
  hosts: all
  connection: local
  vars:
    URL: play.example.com
  tasks:
    - name: Acess a variable
      ansible.builtin.debug:
        msg: URL =={{URL}}

- name: Declare variable in another file
  hosts: all
  connection: local
  vars_files:
    - var.yml
  tasks:

    - name: Acess a vriable
      ansible.builtin.debug:
        msg: URL =={{URL}}



- name: Declare variable at task level
  hosts: all
  connection: local
  tasks:
    - name: Declare and Acess a variable
      ansible.builtin.debug:
        msg: URL =={{URL}}
      vars:
        URL: task.example.com



        # Good